### ISSUE TITLE
Expose the Search engines client

### ISSUE THREAD

**Issue by kerwanp** [FriendsOfAdonis/magnify#3]
## Description

Today, the Search engine clients are stored in a private property of the driver. It is not possible to access them outside of the driver itself.

## Proposition

Each engine should expose its client using a `getter`:

```ts
export class MeilisearchEngine {
  #client: MeiliSearch

  get client(): MeiliSearch {
    return this.#client
  }
}

// Accessible like this
magnify.engine().client
```

**Comment by SimoneStefani** [comment]
Probably worth it to alias `magnify.engine().client` to `magnify.client()` with the option to pass the engine?

**Comment by simoneNEMO** [comment]
Probably worth it to alias `magnify.engine().client` to `magnify.client()` with the option to pass the engine?

**Comment by kerwanp** [comment]
> Probably worth it to alias `magnify.engine().client` to `magnify.client()` with the option to pass the engine?

Might be interesting but some future engines might not have any client like the database engine (Lucid) or the null engine (for tests)
